- platform: mqtt
  name: "Dishwasher"
  command_topic: "shellies/shelly1pm-8CAAB50609DC/relay/0/command"
  state_topic: "shellies/shelly1pm-8CAAB50609DC/relay/0"
  availability_topic: "shellies/shelly1pm-8CAAB50609DC/online"
  payload_on: "on"
  payload_off: "off"
  payload_available: "true"
  payload_not_available: "false"
  qos: 1

- platform: mqtt
  name: "Refrigerator"
  command_topic: "shellies/shellyplug-s-C18ED0/relay/0/command"
  state_topic: "shellies/shellyplug-s-C18ED0/relay/0"
  availability_topic: "shellies/shellyplug-s-C18ED0/online"
  payload_on: "on"
  payload_off: "off"
  payload_available: "true"
  payload_not_available: "false"
  qos: 1

- platform: mqtt
  name: "Freezer"
  command_topic: "shellies/shellyplug-s-A32F96/relay/0/command"
  state_topic: "shellies/shellyplug-s-A32F96/relay/0"
  availability_topic: "shellies/shellyplug-s-A32F96/online"
  payload_on: "on"
  payload_off: "off"
  payload_available: "true"
  payload_not_available: "false"
  qos: 1
