- platform: mqtt
  name: "Towel heater"
  command_topic: "shellies/shellyplug-s-9D8999/relay/0/command"
  state_topic: "shellies/shellyplug-s-9D8999/relay/0"
  availability_topic: "shellies/shellyplug-s-9D8999/online"
  payload_on: "on"
  payload_off: "off"
  payload_available: "true"
  payload_not_available: "false"

- platform: mqtt
  name: "Girls towel heater"
  command_topic: "shellies/shellyplug-s-9D9280/relay/0/command"
  state_topic: "shellies/shellyplug-s-9D9280/relay/0"
  availability_topic: "shellies/shellyplug-s-9D9280/online"
  payload_on: "on"
  payload_off: "off"
  payload_available: "true"
  payload_not_available: "false" 

- platform: mqtt
  name: "Maggie's room heater"
  command_topic: "shellies/shellyplug-s-795A18/relay/0/command"
  state_topic: "shellies/shellyplug-s-795A18/relay/0"
  availability_topic: "shellies/shellyplug-s-795A18/online"
  payload_on: "on"
  payload_off: "off"
  payload_available: "true"
  payload_not_available: "false"
  qos: 1

- platform: mqtt
  name: "Mary's room heater"
  command_topic: "shellies/shellyplug-s-7AEF59/relay/0/command"
  state_topic: "shellies/shellyplug-s-7AEF59/relay/0"
  availability_topic: "shellies/shellyplug-s-7AEF59/online"
  payload_on: "on"
  payload_off: "off"
  payload_available: "true"
  payload_not_available: "false"
  qos: 1

- platform: mqtt
  name: "Main room heater"
  command_topic: "shellies/shellyplug-s-041370/relay/0/command"
  state_topic: "shellies/shellyplug-s-041370/relay/0"
  availability_topic: "shellies/shellyplug-s-041370/online"
  payload_on: "on"
  payload_off: "off"
  payload_available: "true"
  payload_not_available: "false"
  qos: 1

- platform: mqtt
  name: "Living room heater"
  command_topic: "shellies/shellyplug-s-9D9C2A/relay/0/command"
  state_topic: "shellies/shellyplug-s-9D9C2A/relay/0"
  availability_topic: "shellies/shellyplug-s-9D9C2A/online"
  payload_on: "on"
  payload_off: "off"
  payload_available: "true"
  payload_not_available: "false"
  qos: 1

- platform: mqtt
  name: "Kitchen heater"
  command_topic: "shellies/shellyplug-s-9D8B57/relay/0/command"
  state_topic: "shellies/shellyplug-s-9D8B57/relay/0"
  availability_topic: "shellies/shellyplug-s-9D8B57/online"
  payload_on: "on"
  payload_off: "off"
  payload_available: "true"
  payload_not_available: "false"
  qos: 1
