- platform: mqtt
  name: "Towel heater"
  command_topic: "shellies/shellyplug-s-9D8999/relay/0/command"
  state_topic: "shellies/shellyplug-s-9D8999/relay/0"
  availability_topic: "shellies/shellyplug-s-9D8999/online"
  payload_on: "on"
  payload_off: "off"
  payload_available: "true"
  payload_not_available: "false"

- platform: mqtt
  name: "Girls towel heater"
  command_topic: "shellies/shellyplug-s-9D9280/relay/0/command"
  state_topic: "shellies/shellyplug-s-9D9280/relay/0"
  availability_topic: "shellies/shellyplug-s-9D9280/online"
  payload_on: "on"
  payload_off: "off"
  payload_available: "true"
  payload_not_available: "false" 

- platform: mqtt
  name: "MediaRoom main"
  command_topic: "shellies/shellyplug-s-79D245/relay/0/command"
  state_topic: "shellies/shellyplug-s-79D245/relay/0"
  availability_topic: "shellies/shellyplug-s-79D245/online"
  payload_on: "on"
  payload_off: "off"
  payload_available: "true"
  payload_not_available: "false"
  qos: 1

- platform: mqtt
  name: "MediaRoom back"
  command_topic: "shellies/shellyplug-s-04122F/relay/0/command"
  state_topic: "shellies/shellyplug-s-04122F/relay/0"
  availability_topic: "shellies/shellyplug-s-04122F/online"
  payload_on: "on"
  payload_off: "off"
  payload_available: "true"
  payload_not_available: "false"
  qos: 1

- platform: mqtt
  name: "WaterHeating - Gas Heater"
  command_topic: "shellies/shellyplug-s-7AE77A/relay/0/command"
  state_topic: "shellies/shellyplug-s-7AE77A/relay/0"
  availability_topic: "shellies/shellyplug-s-7AE77A/online"
  payload_on: "on"
  payload_off: "off"
  payload_available: "true"
  payload_not_available: "false"
  qos: 1

- platform: mqtt
  name: "Upstairs Dehumidifier"
  command_topic: "shellies/shellyplug-s-021895/relay/0/command"
  state_topic: "shellies/shellyplug-s-021895/relay/0"
  availability_topic: "shellies/shellyplug-s-021895/online"
  payload_on: "on"
  payload_off: "off"
  payload_available: "true"
  payload_not_available: "false"
  qos: 1

- platform: mqtt
  name: "Downstairs Dehumidifier"
  command_topic: "shellies/shellyplug-s-15F511/relay/0/command"
  state_topic: "shellies/shellyplug-s-15F511/relay/0"
  availability_topic: "shellies/shellyplug-s-15F511/online"
  payload_on: "on"
  payload_off: "off"
  payload_available: "true"
  payload_not_available: "false"
  qos: 1


- platform: mqtt
  name: "Maggie's room bed"
  command_topic: "shellies/shellyplug-s-51C884/relay/0/command"
  state_topic: "shellies/shellyplug-s-51C884/relay/0"
  availability_topic: "shellies/shellyplug-s-51C884/online"
  payload_on: "on"
  payload_off: "off"
  payload_available: "true"
  payload_not_available: "false"
  qos: 1

- platform: mqtt
  name: "Maggie's room heater"
  command_topic: "shellies/shellyplug-s-795A18/relay/0/command"
  state_topic: "shellies/shellyplug-s-795A18/relay/0"
  availability_topic: "shellies/shellyplug-s-795A18/online"
  payload_on: "on"
  payload_off: "off"
  payload_available: "true"
  payload_not_available: "false"
  qos: 1

- platform: mqtt
  name: "Mary's room heater"
  command_topic: "shellies/shellyplug-s-7AEF59/relay/0/command"
  state_topic: "shellies/shellyplug-s-7AEF59/relay/0"
  availability_topic: "shellies/shellyplug-s-7AEF59/online"
  payload_on: "on"
  payload_off: "off"
  payload_available: "true"
  payload_not_available: "false"
  qos: 1

- platform: mqtt
  name: "Main room heater"
  command_topic: "shellies/shellyplug-s-041370/relay/0/command"
  state_topic: "shellies/shellyplug-s-041370/relay/0"
  availability_topic: "shellies/shellyplug-s-041370/online"
  payload_on: "on"
  payload_off: "off"
  payload_available: "true"
  payload_not_available: "false"
  qos: 1

- platform: mqtt
  name: "Living room heater"
  command_topic: "shellies/shellyplug-s-9D9C2A/relay/0/command"
  state_topic: "shellies/shellyplug-s-9D9C2A/relay/0"
  availability_topic: "shellies/shellyplug-s-9D9C2A/online"
  payload_on: "on"
  payload_off: "off"
  payload_available: "true"
  payload_not_available: "false"
  qos: 1

- platform: mqtt
  name: "Kitchen heater"
  command_topic: "shellies/shellyplug-s-9D8B57/relay/0/command"
  state_topic: "shellies/shellyplug-s-9D8B57/relay/0"
  availability_topic: "shellies/shellyplug-s-9D8B57/online"
  payload_on: "on"
  payload_off: "off"
  payload_available: "true"
  payload_not_available: "false"
  qos: 1

- platform: mqtt
  name: "Fly frier"
  command_topic: "shellies/shellyplug-s-9D8E59/relay/0/command"
  state_topic: "shellies/shellyplug-s-9D8E59/relay/0"
  availability_topic: "shellies/shellyplug-s-9D8E59/online"
  payload_on: "on"
  payload_off: "off"
  payload_available: "true"
  payload_not_available: "false"
  qos: 1

- platform: mqtt
  name: "Living Room Media - Smart"
  command_topic: "shellies/shellyplug-s-A415BD/relay/0/command"
  state_topic: "shellies/shellyplug-s-A415BD/relay/0"
  availability_topic: "shellies/shellyplug-s-A415BD/online"
  payload_on: "on"
  payload_off: "off"
  payload_available: "true"
  payload_not_available: "false"
  qos: 1

- platform: mqtt
  name: "Living Room Media - Comms"
  command_topic: "shellies/shellyplug-s-C18CAD/relay/0/command"
  state_topic: "shellies/shellyplug-s-C18CAD/relay/0"
  availability_topic: "shellies/shellyplug-s-C18CAD/online"
  payload_on: "on"
  payload_off: "off"
  payload_available: "true"
  payload_not_available: "false"
  qos: 1

- platform: mqtt
  name: "Office Datacenter"
  command_topic: "shellies/shellyplug-s-C133B7/relay/0/command"
  state_topic: "shellies/shellyplug-s-C133B7/relay/0"
  availability_topic: "shellies/shellyplug-s-C133B7/online"
  payload_on: "on"
  payload_off: "off"
  payload_available: "true"
  payload_not_available: "false"
  qos: 1




