- platform: mqtt
  unique_id: status_familysleeping
  name: "Status - Family Sleeping"
  command_topic: "home/l/status/family_asleep"
  state_topic: "home/l/status/family_asleep"
  icon: mdi:toggle-switch-outline
  qos: 1
  retain: true

- platform: mqtt
  name: "Status - Family Asleep - HasRunToday"
  command_topic: "home/l/status/family_asleep_runtoday"
  state_topic: "home/l/status/family_asleep_runtoday"
  icon: mdi:toggle-switch-outline
  qos: 1
  retain: true

- platform: mqtt
  name: "Status - Family Wakeup - HasRunToday"
  command_topic: "home/l/status/family_wakeup_runtoday"
  state_topic: "home/l/status/family_wakeup_runtoday"
  icon: mdi:toggle-switch-outline
  qos: 1
  retain: true
