- platform: wake_on_lan
  mac: !secret wol_srv1_mac
  name: devices_srv01_wol
  host: !secret wol_srv1_ip

- platform: command_line
  switches:
    devices_srv01_poweroff:
      command_off: !secret srv1_shutdown

- platform: template
  switches:
    d_srv01_switch:
      friendly_name: "HP Server"
#     value_template: "{{ is_state('switch.devices_srv01_wol', 'on') }}"
      value_template: "{% if is_state('switch.devices_srv01_wol', 'on') %}on{% else %}off{% endif %}"
      turn_on:
        service: switch.turn_on
        entity_id: switch.devices_srv01_wol
      turn_off:
        service: switch.turn_off
        entity_id: switch.devices_srv01_poweroff
