- platform: bayesian
  name: family_asleep2
  prior: 0.33
  probability_threshold: 0.8
  observations:
    - platform: 'state'
      entity_id: 'group.lights_downstairs'
      prob_given_true: 1
      prob_given_false: 0.60
      to_state: 'off'
    - platform: 'state'
      entity_id: 'group.motion_downstairs'
      prob_given_true: 1
      prob_given_false: 0.6
      to_state: 'off'
    - platform: template
      value_template: '{{(states("sensor.time").split(":")[0]) |int >=22 or (states("sensor.time").split(":")[0]) |int  <= 6}}'
      prob_given_true: 0.8
      prob_given_false: 0.2
#    - platform: 'state'
#      entity_id: 'group.family'
#      prob_given_true: 1
#      prob_given_false: 0.66
#      to_state: 'home'

- platform: mqtt
  name: "Front Door Contact Sensor"
  state_topic: "shellies/shellydw2-A4CF12F42F72/sensor/state"
  payload_on: "open"
  payload_off: "close"
  device_class: door

- platform: mqtt
  name: "Sliding Gate Contact Sensor"
  state_topic: "shellies/shellydw2-40F5202E46FF/sensor/state"
  payload_on: "open"
  payload_off: "close"
  device_class: door

- platform: mqtt
  name: "Garage Door Contact Sensor"
  state_topic: "shellies/shellydw2-40F5202E104F/sensor/state"
  payload_on: "open"
  payload_off: "close"
  device_class: garage_door







