- platform: template
  sensors:
    waterheating_gas_heater_state:
      friendly_name: "WaterHeating - Gas Heater State"
      delay_on:
          seconds: 30
      delay_off:
          seconds: 30
      value_template: "{{states('sensor.waterheating_gas_heater_power')|float > 10}}"
