- platform: template
  sensors:
    presence_cinemaroom:
      delay_off:
          minutes: 5
      value_template: "{{is_state('binary_sensor.f5im51_101_20','on')}}"
      
    presence_downhall:
      friendly_name: "Down hall presence"
      delay_off:
          minutes: 5
      value_template: "{{is_state('binary_sensor.f5im51_102_20','on')}}"

    presence_kitchen:
      delay_off:
          minutes: 5
      value_template: "{{is_state('binary_sensor.f5im51_104_20','on')}}"
  
