- platform: mqtt
  name: GardenZone1 Conductivity
  state_topic: "home/l/garden/harega/pub/sensor/ble_conductivity_c47c8d665630/state"
  unit_of_measurement: "µS/cm"

- platform: mqtt
  name: GardenZone1 Moisture
  state_topic: "home/l/garden/harega/pub/sensor/ble_moisture_c47c8d665630/state"
  unit_of_measurement: "%"

- platform: mqtt
  name: GardenZone1 Temperature
  state_topic: "home/l/garden/harega/pub/sensor/ble_temperature_c47c8d665630/state"
  unit_of_measurement: "°C"

- platform: mqtt
  name: GardenZone2 Conductivity
  state_topic: "home/l/garden/harega/pub/sensor/ble_conductivity_c47c8d6c8839/state"
  unit_of_measurement: "µS/cm"

- platform: mqtt
  name: GardenZone2 Moisture
  state_topic: "home/l/garden/harega/pub/sensor/ble_moisture_c47c8d6c8839/state"
  unit_of_measurement: "%"

- platform: mqtt
  name: GardenZone2 Temperature
  state_topic: "home/l/garden/harega/pub/sensor/ble_temperature_c47c8d6c8839/state"
  unit_of_measurement: "°C"

- platform: mqtt
  name: GardenZone3 Conductivity
  state_topic: "home/l/garden/harega/pub/sensor/ble_conductivity_c47c8d6c987d/state"
  unit_of_measurement: "µS/cm"

- platform: mqtt
  name: GardenZone3 Moisture
  state_topic: "home/l/garden/harega/pub/sensor/ble_moisture_c47c8d6c987d/state"
  unit_of_measurement: "%"

- platform: mqtt
  name: GardenZone3 Temperature
  state_topic: "home/l/garden/harega/pub/sensor/ble_temperature_c47c8d6c987d/state"
  unit_of_measurement: "°C"

- platform: mqtt
  name: GardenWaterDepositSensor
  state_topic: "home/l/garden/harega/pub/sensor/f_wtm51_15_20/state"
  unit_of_measurement: "cm"


