- platform: integration
  source: sensor.huawei_pv_power
  name: huawei_pv_energy
  round: 3

- platform: statistics
  name: Washmachine Power Stats
  entity_id:  sensor.washing_machine_power
  sampling_size: 20
  state_characteristic: mean

- platform: statistics
  name: Washmachine Power Stats - average_linear
  entity_id:  sensor.washing_machine_power
  sampling_size: 20
  state_characteristic: average_linear

- platform: statistics
  name: Washmachine Power Stats - average_step
  entity_id:  sensor.washing_machine_power
  sampling_size: 20
  state_characteristic: average_step

#- platform: statistics
#  name: Washmachine Power Stats - percentile
#  entity_id:  sensor.washing_machine_power
#  sampling_size: 20
#  state_characteristic: percentile
#  percentile: 75


- platform: statistics
  name: Drymachine Power Stats
  entity_id: sensor.shellyp1pm_drymachine_switch_0_power
  sampling_size: 20
  state_characteristic: average_step

- platform: statistics
  name: Drymachine Power Stats - average_linear
  entity_id:  sensor.shellyp1pm_drymachine_switch_0_power
  sampling_size: 20
  state_characteristic: average_linear

- platform: statistics
  name: Drymachine Power Stats - average_step
  entity_id: sensor.shellyp1pm_drymachine_switch_0_power
  sampling_size: 20
  state_characteristic: average_step


- platform: statistics
  name: Living room media Power Stats
  entity_id: sensor.power_living_room_smart
  sampling_size: 20
  state_characteristic: mean
  max_age:
    minutes: 2

- platform: statistics
  name: CO2 Stats
  entity_id:  sensor.f_5im51_102_30
  sampling_size: 20
  state_characteristic: mean