- platform: mqtt
  name: "WaterHeating - Gas Heater Power"
  state_topic: "shellies/shellyplug-s-7AE77A/relay/0/power"
  availability_topic: "shellies/shellyplug-s-7AE77A/online"
  unit_of_measurement: "W"
  payload_available: "true"
  payload_not_available: "false"
  force_update: "true"






