- platform: mqtt
  name: Washing machine power
  state_topic: "shellies/shelly1pm-8CAAB5060859/relay/0/power"
  availability_topic: "shellies/shelly1pm-8CAAB5060859/online"
  payload_available: "true"
  payload_not_available: "false"
  unit_of_measurement: "W"

- platform: mqtt
  name: Drying machine power
  state_topic: "shellies/shelly1pm-C4AA7A/relay/0/power"
  availability_topic: "shellies/shelly1pm-C4AA7A/online"
  unit_of_measurement: "W"
  payload_available: "true"
  payload_not_available: "false"

- platform: mqtt
  name: Refrigerator power
  state_topic: "shellies/shellyplug-s-C18ED0/relay/0/power"
  availability_topic: "shellies/shellyplug-s-C18ED0/online"
  unit_of_measurement: "W"
  payload_available: "true"
  payload_not_available: "false"

- platform: mqtt
  name: Freezer power
  state_topic: "shellies/shellyplug-s-A32F96/relay/0/power"
  availability_topic: "shellies/shellyplug-s-A32F96/online"
  unit_of_measurement: "W"
  payload_available: "true"
  payload_not_available: "false"

- platform: mqtt
  name: Dishwasher power
  state_topic: "shellies/shelly1pm-8CAAB50609DC/relay/0/power"
  availability_topic: "shellies/shelly1pm-8CAAB50609DC/online"
  unit_of_measurement: "W"
  payload_available: "true"
  payload_not_available: "false"

- platform: mqtt
  name: Power - Office Datacenter
  state_topic: "shellies/shellyplug-s-C133B7/relay/0/power"
  availability_topic: "shellies/shellyplug-s-C133B7/online"
  unit_of_measurement: "W"
  payload_available: "true"
  payload_not_available: "false"

- platform: mqtt
  name: Power - Living Room - Smart
  state_topic: "shellies/shellyplug-s-A415BD/relay/0/power"
  availability_topic: "shellies/shellyplug-s-A415BD/online"
  unit_of_measurement: "W"
  payload_available: "true"
  payload_not_available: "false"

- platform: mqtt
  name: Power - Living Room - Comms
  state_topic: "shellies/shellyplug-s-C18CAD/relay/0/power"
  availability_topic: "shellies/shellyplug-s-C18CAD/online"
  unit_of_measurement: "W"
  payload_available: "true"
  payload_not_available: "false"

- platform: mqtt
  name: "Power - Towel heater"
  state_topic: "shellies/shellyplug-s-9D8999/relay/0/power"
  availability_topic: "shellies/shellyplug-s-9D8999/online"
  unit_of_measurement: "W"
  payload_available: "true"
  payload_not_available: "false"

- platform: mqtt
  name: "Power - Girls towel heater"
  state_topic: "shellies/shellyplug-s-9D9280/relay/0/power"
  availability_topic: "shellies/shellyplug-s-9D9280/online"
  unit_of_measurement: "W"
  payload_available: "true"
  payload_not_available: "false" 

- platform: mqtt
  name: "Power - Maggie's room heater"
  state_topic: "shellies/shellyplug-s-795A18/relay/0/power"
  availability_topic: "shellies/shellyplug-s-795A18/online"
  unit_of_measurement: "W"
  payload_available: "true"
  payload_not_available: "false"

- platform: mqtt
  name: "Power - Mary's room heater"
  state_topic: "shellies/shellyplug-s-7AEF59/relay/0/power"
  availability_topic: "shellies/shellyplug-s-7AEF59/online"
  unit_of_measurement: "W"
  payload_available: "true"
  payload_not_available: "false"

- platform: mqtt
  name: "Power - Main room heater"
  state_topic: "shellies/shellyplug-s-041370/relay/0/power"
  availability_topic: "shellies/shellyplug-s-041370/online"
  unit_of_measurement: "W"
  payload_available: "true"
  payload_not_available: "false"

- platform: mqtt
  name: "Power - Living room heater"
  state_topic: "shellies/shellyplug-s-9D9C2A/relay/0/power"
  availability_topic: "shellies/shellyplug-s-9D9C2A/online"
  unit_of_measurement: "W"
  payload_available: "true"
  payload_not_available: "false"

- platform: mqtt
  name: "Power - Kitchen heater"
  state_topic: "shellies/shellyplug-s-9D8B57/relay/0/power"
  availability_topic: "shellies/shellyplug-s-9D8B57/online"
  unit_of_measurement: "W"
  payload_available: "true"
  payload_not_available: "false"

- platform: mqtt
  name: "Power - Car charger"
  state_topic: "shellies/shellyem-BCFF4DFCE0F5/emeter/0/power"
  availability_topic: "shellies/shellyem-BCFF4DFCE0F5/online"
  unit_of_measurement: "W"
  payload_available: "true"
  payload_not_available: "false"








