- platform: mqtt
  name: Solar heater backup power
  state_topic: "shellies/shelly1pm-F306C1/relay/0/power"
#  availability_topic: "shellies/shelly1pm-F306C1/online"
  unit_of_measurement: "W"
#  payload_available: "true"
#  payload_not_available: "false"

- platform: mqtt
  name: Solar heater water temperature
  state_topic: "shellies/shelly1pm-F306C1/ext_temperature/0"
#  availability_topic: "shellies/shelly1pm-F306C1/online"
  unit_of_measurement: "°C"
#  payload_available: "true"
#  payload_not_available: "false"
  device_class: temperature
  value_template: "{{value | float + 5}}"

- platform: mqtt
  name: Solar heater last sanitized
  state_topic: "home/l/data/solpanelsanitized"
