# Weather Prediction
- platform: time_date
  display_options:
    - 'time'
    - 'date'

- platform: template
  sensors:
    weather_todayforecastcondition:
      entity_id: weather.loures
      value_template: "{{state_attr('weather.loures','forecast')[0].condition}}"

#- platform: yweather
#  woeid: 742823
#  forecast: 1
#  name: w_forecast
#  monitored_conditions:
#    - weather
#    - temp_min
#    - temp_max




