- platform: template
  covers:
    garage_door:
      device_class: garage
      friendly_name: "Garage Door"
      value_template: "{{ states('binary_sensor.garage_door_contact_sensor') == 'on'}}"
      open_cover:
        service: switch.turn_on
        target:
          entity_id: switch.garage_door_control
      close_cover:
        service: switch.turn_on
        target:
          entity_id: switch.garage_door_control
      stop_cover:
        service: switch.turn_on
        target:
          entity_id: switch.garage_door_control
      icon_template: >-
        {% if (states('binary_sensor.sliding_gate_contact_sensor') == 'on') %}
          mdi:garage-open
        {% else %}
          mdi:garage
        {% endif %}

    driveway:
      device_class: gate
      friendly_name: "Driveway"
      value_template: "{{ states('binary_sensor.sliding_gate_contact_sensor') == 'on' }}"
      open_cover:
        service: switch.turn_on
        target:
          entity_id: switch.sliding_gate_control
      close_cover:
        service: switch.turn_on
        target:
          entity_id: switch.sliding_gate_control
      stop_cover:
        service: switch.turn_on
        target:
          entity_id: switch.sliding_gate_control
      icon_template: >-
        {% if (states('binary_sensor.sliding_gate_contact_sensor') == 'on') %}
          mdi:gate-open
        {% else %}
          mdi:gate
        {% endif %}
