- alias: 'WashingMachineFinished'
  trigger:
    platform: state
    entity_id: binary_sensor.washmachine_state
    from: 'on'
    to: 'off'
  action:
    - service: notify.all_mobiles
      data:
        message: "Washing machine finished..."
    - condition: state
      entity_id: 'switch.preference_noisy_automations'
      state: 'on'
    - service: notify.alexa_media
      data:
        target:
          - media_player.everywhere
        message: "<voice name='Ines'><lang xml:lang='pt-PT'>Ol치! A m치quina de lavar terminou.</lang></voice>"
        data:
          type: announce
          method: all


- alias: 'DryingMachineFinished'
  trigger:
    platform: state
    entity_id: binary_sensor.drymachine_state
    from: 'on'
    to: 'off'
  action:
    - service: notify.all_mobiles
      data:
        message: "Drying machine finished..."
    - condition: state
      entity_id: 'switch.preference_noisy_automations'
      state: 'on'
    - service: notify.alexa_media
      data:
        target:
          - media_player.everywhere
        message: "<voice name='Ines'><lang xml:lang='pt-PT'>Ol치! A m치quina de secar terminou.</lang></voice>"
        data:
          type: announce
          method: all

