- alias: 'Blinds/UpdatePosition'
  id: '2021110700001'
  trigger:
    - platform: numeric_state
      entity_id: sun.sun
      attribute: azimuth
      above: 150
    - platform: numeric_state
      entity_id: sun.sun
      attribute: azimuth
      above: 210
    - platform: numeric_state
      entity_id: sun.sun
      attribute: elevation
      above: 1
    - platform: sun
      event: sunset
      offset: "-00:30:00"
    - platform: state
      entity_id: switch.preference_noisy_automations
      from: 'off'
      to: 'on'
      for:
        seconds: 10 
    - platform: state
      entity_id: group.family
      from: 'home'
      to: 'not_home'
      for:
        minutes: 5
    - platform: state
      entity_id: group.family
      from: 'not_home'
      to: 'home'
      for:
        minutes: 5
    - platform: template
      value_template: '{{(states.sensor.upstairs_temp.state | float) > (states.sensor.outside_temperature.state | float - 2)}}'
    - platform: template
      value_template: '{{(states.sensor.upstairs_temp.state | float) < (states.sensor.outside_temperature.state | float - 2)}}'
  condition:
      - condition: state
        entity_id: 'switch.preference_shutters_automation'
        state: 'on'
      - condition: state
        entity_id: 'switch.preference_noisy_automations'
        state: 'on'
      - condition: state
        entity_id: 'input_boolean.mode_visitors'
        state: 'off'
      - condition: state
        entity_id: 'input_boolean.mode_guests'
        state: 'off'
  action:
    - choose:
      - alias: "Summer/FamilyNotHome/Morning"
        conditions:
        - condition: state
          entity_id: input_select.mode_climate
          state: 'Summer'
        - condition: state
          entity_id: 'group.family'
          state: 'not_home'
        - condition: sun
          before: sunset
          before_offset: "-00:35:00"
        - condition: numeric_state
          entity_id: sun.sun
          attribute: elevation
          above: 1
        - condition: numeric_state
          entity_id: sun.sun
          attribute: azimuth
          above: 150
        - condition: template
          value_template: '{{ (states.sensor.upstairs_temp.state | float) > (states.sensor.outside_temperature.state | float - 1) }}'
        sequence:
          - service: script.turn_on
            entity_id: script.shutter_open_group
            data:
              variables:
                group: group.shutters_eastup
                normal: 75
                bright: 85
                safe: 5
          - service: script.turn_on
            entity_id: script.shutter_close_group
            data:
              variables:
                group: group.shutters_southup
                normal: 0
                bright: 10
                safe: 0

      - alias: "Summer/FamilyNotHome/Noon"
        conditions:
        - condition: state
          entity_id: input_select.mode_climate
          state: 'Summer'
        - condition: state
          entity_id: 'group.family'
          state: 'not_home'
        - condition: sun
          before: sunset
          before_offset: "-00:35:00"
        - condition: numeric_state
          entity_id: sun.sun
          attribute: azimuth
          above: 150
        - condition: template
          value_template: '{{ (states.sensor.upstairs_temp.state | float) > (states.sensor.outside_temperature.state | float - 1) }}'
        sequence:
          - service: script.turn_on
            entity_id: script.shutter_open_group
            data:
              variables:
                group: group.shutters_eastup
                normal: 75
                bright: 85
                safe: 5
          - service: script.turn_on
            entity_id: script.shutter_close_group
            data:
              variables:
                group: group.shutters_southup
                normal: 0
                bright: 10
                safe: 0

      - alias: "Summer/FamilyHome/Morning"
        conditions:
        - condition: state
          entity_id: input_select.mode_climate
          state: 'Summer'
        - condition: state
          entity_id: 'group.family'
          state: 'home'
        - condition: state
          entity_id: 'input_boolean.mode_automate_b_whenhome'
          state: 'on'
        - condition: sun
          before: sunset
          before_offset: "-01:00:00"
        - condition: numeric_state
          entity_id: sun.sun
          attribute: azimuth
          below: 150
        sequence:
          - service: script.turn_on
            entity_id: script.shutter_open_group
            data:
              variables:
                group: group.shutters_northdown
                normal: 85
                bright: 90
                safe: 5
          - service: script.turn_on
            entity_id: script.shutter_open_group
            data:
              variables:
                group: group.shutters_southup
                normal: 85
                bright: 35
                safe: 5
          - service: script.turn_on
            entity_id: script.shutter_open_group
            data:
              variables:
                group: group.shutters_eastup
                normal: 85
                bright: 35
                safe: 5
          - service: script.turn_on
            entity_id: script.shutter_open_group
            data:
              variables:
                group: group.shutters_eastdown
                normal: 85
                bright: 35
                safe: 5
          - service: script.turn_on
            entity_id: script.shutter_open_group
            data:
              variables:
                group: group.shutters_westup
                normal: 85
                bright: 90
                safe: 15
          - service: script.turn_on
            entity_id: script.shutter_open_group
            data:
               variables:
                group: group.shutters_westdown
                normal: 85
                bright: 90
                safe: 15
          - service: script.turn_on
            entity_id: script.shutter_open_group
            data:
               variables:
                group: group.shutters_kitchen
                normal: 85
                bright: 90
                safe: 15

 
      - alias: "Summer/Open/FamilyHome/Afternoon"
        conditions:
        - condition: state
          entity_id: input_select.mode_climate
          state: 'Summer'
        - condition: state
          entity_id: 'group.family'
          state: 'home'
        - condition: state
          entity_id: 'input_boolean.mode_automate_b_whenhome'
          state: 'on'
        - condition: sun
          before: sunset
          before_offset: "-00:35:00"
        - condition: numeric_state
          entity_id: sun.sun
          attribute: azimuth
          above: 150
        sequence:
          - service: script.turn_on
            entity_id: script.shutter_open_group
            data:
              variables:
                group: group.shutters_northdown
                normal: 85
                bright: 90
                safe: 5
          - service: script.turn_on
            entity_id: script.shutter_open_group
            data:
              variables:
                group: group.shutters_southup
                normal: 85
                bright: 35
                safe: 5
          - service: script.turn_on
            entity_id: script.shutter_open_group
            data:
              variables:
                group: group.shutters_eastup
                normal: 85
                bright: 90
                safe: 5
          - service: script.turn_on
            entity_id: script.shutter_open_group
            data:
              variables:
                group: group.shutters_eastdown
                normal: 85
                bright: 90
                safe: 5
          - service: script.turn_on
            entity_id: script.shutter_close_group
            data:
              variables:
                group: group.shutters_westup
                normal: 85
                bright: 35
                safe: 0
          - service: script.turn_on
            entity_id: script.shutter_close_group
            data:
              variables:
                group: group.shutters_westdown
                normal: 85
                bright: 35
                safe: 0

      - alias: "Winter/FamilyNotHome/Morning"
        conditions:
        - condition: state
          entity_id: input_select.mode_climate
          state: 'Winter'
        - condition: state
          entity_id: 'group.family'
          state: 'not_home'
        - condition: sun
          before: sunset
          before_offset: "-00:35:00"
        - condition: numeric_state
          entity_id: sun.sun
          attribute: elevation
          above: 1
        - condition: numeric_state
          entity_id: sun.sun
          attribute: azimuth
          above: 150
        sequence:
          - service: script.turn_on
            entity_id: script.shutter_open_group
            data:
              variables:
                group: group.shutters_westup
                normal: 75
                bright: 85
                safe: 5
          - service: script.turn_on
            entity_id: script.shutter_close_group
            data:
              variables:
                group: group.shutters_southup
                normal: 0
                bright: 10
                safe: 0

      - alias: "Winter/FamilyNotHome/Noon"
        conditions:
        - condition: state
          entity_id: input_select.mode_climate
          state: 'Winter'
        - condition: state
          entity_id: 'group.family'
          state: 'not_home'
        - condition: sun
          before: sunset
          before_offset: "-00:35:00"
        - condition: numeric_state
          entity_id: sun.sun
          attribute: azimuth
          above: 150
        sequence:
          - service: script.turn_on
            entity_id: script.shutter_open_group
            data:
              variables:
                group: group.shutters_westup
                normal: 75
                bright: 85
                safe: 5
          - service: script.turn_on
            entity_id: script.shutter_close_group
            data:
              variables:
                group: group.shutters_southup
                normal: 0
                bright: 10
                safe: 0

      - alias: "Winter/FamilyHome/Morning"
        conditions:
        - condition: state
          entity_id: input_select.mode_climate
          state: 'Winter'
        - condition: state
          entity_id: 'group.family'
          state: 'home'
        - condition: state
          entity_id: 'input_boolean.mode_automate_b_whenhome'
          state: 'on'
        - condition: sun
          before: sunset
          before_offset: "-01:00:00"
        - condition: numeric_state
          entity_id: sun.sun
          attribute: azimuth
          below: 150
        sequence:
          - service: script.turn_on
            entity_id: script.shutter_open_group
            data:
              variables:
                group: group.shutters_northdown
                normal: 85
                bright: 90
                safe: 5
          - service: script.turn_on
            entity_id: script.shutter_open_group
            data:
              variables:
                group: group.shutters_southup
                normal: 85
                bright: 35
                safe: 5
          - service: script.turn_on
            entity_id: script.shutter_open_group
            data:
              variables:
                group: group.shutters_westup
                normal: 85
                bright: 35
                safe: 5
          - service: script.turn_on
            entity_id: script.shutter_open_group
            data:
              variables:
                group: group.shutters_westdown
                normal: 85
                bright: 35
                safe: 5
          - service: script.turn_on
            entity_id: script.shutter_open_group
            data:
              variables:
                group: group.shutters_eastup
                normal: 85
                bright: 90
                safe: 15
          - service: script.turn_on
            entity_id: script.shutter_open_group
            data:
               variables:
                group: group.shutters_eastdown
                normal: 85
                bright: 90
                safe: 15
          - service: script.turn_on
            entity_id: script.shutter_open_group
            data:
               variables:
                group: group.shutters_kitchen
                normal: 100
                bright: 100
                safe: 15

 
      - alias: "Winter/Open/FamilyHome/Afternoon"
        conditions:
        - condition: state
          entity_id: input_select.mode_climate
          state: 'Winter'
        - condition: state
          entity_id: 'group.family'
          state: 'home'
        - condition: state
          entity_id: 'input_boolean.mode_automate_b_whenhome'
          state: 'on'
        - condition: sun
          before: sunset
          before_offset: "-00:35:00"
        - condition: numeric_state
          entity_id: sun.sun
          attribute: azimuth
          above: 150
        sequence:
          - service: script.turn_on
            entity_id: script.shutter_open_group
            data:
              variables:
                group: group.shutters_northdown
                normal: 85
                bright: 90
                safe: 5
          - service: script.turn_on
            entity_id: script.shutter_open_group
            data:
              variables:
                group: group.shutters_southup
                normal: 85
                bright: 35
                safe: 5
          - service: script.turn_on
            entity_id: script.shutter_open_group
            data:
              variables:
                group: group.shutters_westup
                normal: 85
                bright: 90
                safe: 5
          - service: script.turn_on
            entity_id: script.shutter_open_group
            data:
              variables:
                group: group.shutters_westdown
                normal: 85
                bright: 90
                safe: 5
          - service: script.turn_on
            entity_id: script.shutter_close_group
            data:
              variables:
                group: group.shutters_eastup
                normal: 85
                bright: 35
                safe: 0
          - service: script.turn_on
            entity_id: script.shutter_close_group
            data:
              variables:
                group: group.shutters_eastdown
                normal: 85
                bright: 35
                safe: 0


#- alias: 'Notify blinds still open'
#  trigger:
#    platform: sun
#    event: sunset
#    offset: "-00:30:00"
#  condition:
#    condition: and
#    conditions:
#      - condition: state
#        entity_id: 'group.shutters_all'
#        state: 'open'
#  action:
#    - service: notify.all_mobiles
#      data:
#        message: "Sun is setting, blinds should be closed."        

#- alias: 'Blinds/All/Notification/Close'
#  trigger:
#    - platform: event
#      event_type: ios.notification_action_fired
#      event_data:
#        actionName: CLOSE_BLINDS
#    - platform: event
#      event_type: html5_notification.clicked
#      event_data:
#        action: close_blinds
#  action:
#    service: cover.close_cover
#    entity_id: group.shutters_all

- alias: 'Blinds/All/HouseEmpty/Close'
  trigger:
    - platform: sun
      event: sunset
      offset: "-01:00:00"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: 'group.family'
        state: 'not_home'
      - condition: state
        entity_id: 'input_boolean.mode_visitors'
        state: 'off'
      - condition: state
        entity_id: 'input_boolean.mode_guests'
        state: 'off'
  action:
    service: cover.close_cover
    entity_id: group.shutters_all

- alias: 'Blinds/All/Sunset/Close'
  trigger:
    - platform: sun
      event: sunset
      offset: "-00:15:00"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: 'group.shutters_all'
        state: 'open'

      - condition: state
        entity_id: 'input_boolean.mode_holidays'
        state: 'off'
      - condition: state
        entity_id: 'switch.preference_shutters_automation'
        state: 'on'
  action:
    - service: notify.alexa_media
      data:
        target:
          - media_player.everywhere
        message: "<prosody volume='x-loud'><emphasis>Warning!</emphasis></prosody>Window shutters will be closing in five minutes."
        data:
          type: announce
          method: all
    - delay: 0:04
    - service: notify.alexa_media
      data:
        target:
          - media_player.everywhere
        message: "<prosody volume='x-loud'><emphasis>Warning!</emphasis></prosody>Window shutters will be closing in one minute."
        data:
          type: announce
          method: all
    - delay: 0:01
    - service: cover.close_cover
      entity_id: group.shutters_all
#    - service: cover.close_cover
#      entity_id: group.shutters_kitchen


