- alias: 'Climate/Thermostats/Rooms/IncreaseBeforeBed'
  trigger:
    - platform: time
      at: "20:00:00"
  action:
    - service: climate.set_temperature
      entity_id: climate.maggie_s_room_thermostat
      data_template:
        temperature: "{{state_attr('climate.maggie_s_room_thermostat','temperature') | float + 0.5}}"
    - service: climate.set_temperature
      entity_id: climate.mary_s_room_thermostat
      data_template:
        temperature: "{{state_attr('climate.mary_s_room_thermostat','temperature') | float + 0.5}}"
    - service: climate.set_temperature
      entity_id: climate.main_room_thermostat
      data_template:
        temperature: "{{state_attr('climate.main_room_thermostat','temperature') | float + 0.5}}"

- alias: 'Climate/Thermostats/Rooms/DecreaseAfterSleep'
  trigger:
    - platform: state
      entity_id: 'switch.status_family_sleeping'
      to: "on"
      for: "01:00:00"
  action:
    - service: climate.set_temperature
      entity_id: climate.maggie_s_room_thermostat
      data_template:
        temperature: "{{state_attr('climate.maggie_s_room_thermostat','temperature') | float - 1}}"
    - service: climate.set_temperature
      entity_id: climate.mary_s_room_thermostat
      data_template:
        temperature: "{{state_attr('climate.mary_s_room_thermostat','temperature') | float - 1}}"
    - service: climate.set_temperature
      entity_id: climate.main_room_thermostat
      data_template:
        temperature: "{{state_attr('climate.main_room_thermostat','temperature') | float - 1}}"

- alias: 'Climate/Thermostats/Rooms/IncreaseBeforeWakeup'
  trigger:
    - platform: time
      at: "05:00:00"
  action:
    - service: climate.set_temperature
      entity_id: climate.maggie_s_room_thermostat
      data_template:
        temperature: "{{state_attr('climate.maggie_s_room_thermostat','temperature') | float + 0.5}}"
    - service: climate.set_temperature
      entity_id: climate.mary_s_room_thermostat
      data_template:
        temperature: "{{state_attr('climate.mary_s_room_thermostat','temperature') | float + 0.5}}"
    - service: climate.set_temperature
      entity_id: climate.main_room_thermostat
      data_template:
        temperature: "{{state_attr('climate.main_room_thermostat','temperature') | float + 0.5}}"


- alias: 'Climate/Thermostats/Rooms/DecreaseAfterWakeup'
  trigger:
    - platform: state
      entity_id: 'switch.status_family_sleeping'
      to: "off"
      for: "00:30:00"
  action:
    - service: climate.set_temperature
      entity_id: climate.maggie_s_room_thermostat
      data_template:
        temperature: "{{state_attr('climate.maggie_s_room_thermostat','temperature') | float - 1}}"
    - service: climate.set_temperature
      entity_id: climate.mary_s_room_thermostat
      data_template:
        temperature: "{{state_attr('climate.mary_s_room_thermostat','temperature') | float - 1}}"
    - service: climate.set_temperature
      entity_id: climate.main_room_thermostat
      data_template:
        temperature: "{{state_attr('climate.main_room_thermostat','temperature') | float - 1}}"


- alias: 'Climate/Thermostats/Rooms/IncreaseAtSunset'
  trigger:
    platform: sun
    event: sunset
    offset: "00:30:00"
  action:
    - service: climate.set_temperature
      entity_id: climate.maggie_s_room_thermostat
      data_template:
        temperature: "{{state_attr('climate.maggie_s_room_thermostat','temperature') | float + 1}}"
    - service: climate.set_temperature
      entity_id: climate.mary_s_room_thermostat
      data_template:
        temperature: "{{state_attr('climate.mary_s_room_thermostat','temperature') | float + 1}}"
    - service: climate.set_temperature
      entity_id: climate.main_room_thermostat
      data_template:
        temperature: "{{state_attr('climate.main_room_thermostat','temperature') | float + 1}}"


- alias: 'Climate/Thermostats/LivingAreas/IncreaseAfterWakeup'
  trigger:
    - platform: state
      entity_id: 'switch.status_family_sleeping'
      to: "off"
  action:
    - service: climate.set_temperature
      entity_id: climate.living_room_thermostat
      data_template:
        temperature: "{{state_attr('climate.living_room_thermostat','temperature') | float + 0.5}}"
    - service: climate.set_temperature
      entity_id: climate.kitchen_thermostat
      data_template:
        temperature: "{{state_attr('climate.kitchen_thermostat','temperature') | float + 0.5}}"

- alias: 'Climate/Thermostats/LivingAreas/IncreaseAtSunset'
  trigger:
    platform: sun
    event: sunset
    offset: "-00:30:00"
  action:
    - service: climate.set_temperature
      entity_id: climate.living_room_thermostat
      data_template:
        temperature: "{{state_attr('climate.living_room_thermostat','temperature') | float + 0.5}}"
    - service: climate.set_temperature
      entity_id: climate.kitchen_thermostat
      data_template:
        temperature: "{{state_attr('climate.kitchen_thermostat','temperature') | float + 0.5}}"

- alias: 'Climate/Thermostats/LivingAreas/DecreaseAfterSleep'
  trigger:
    - platform: state
      entity_id: 'switch.status_family_sleeping'
      to: "on"
  action:
    - service: climate.set_temperature
      entity_id: climate.living_room_thermostat
      data_template:
        temperature: "{{state_attr('climate.living_room_thermostat','temperature') | float - 1}}"
    - service: climate.set_temperature
      entity_id: climate.kitchen_thermostat
      data_template:
        temperature: "{{state_attr('climate.kitchen_thermostat','temperature') | float - 1}}"






#- alias: 'Climate/Thermostats/IncreaseOnOffpeak'
#  trigger:
#    - platform: state
#      entity_id: sensor.electricity_rate
#      from: "Peak"
#      to: "Off-peak"
#  action:
#    - service: climate.set_temperature
#      entity_id: climate.living_room_thermostat
#      data_template:
#        temperature: "{{state_attr('climate.living_room_thermostat','temperature') | float + 0.5}}"
#    - service: climate.set_temperature
#      entity_id: climate.maggie_s_room_thermostat
#      data_template:
#        temperature: "{{state_attr('climate.maggie_s_room_thermostat','temperature') | float + 0.5}}"
#    - service: climate.set_temperature
#      entity_id: climate.mary_s_room_thermostat
#      data_template:
#        temperature: "{{state_attr('climate.mary_s_room_thermostat','temperature') | float + 0.5}}"
#    - service: climate.set_temperature
#      entity_id: climate.main_room_thermostat
#      data_template:
#        temperature: "{{state_attr('climate.main_room_thermostat','temperature') | float + 0.5}}"


- alias: 'Climate/ClimateMode/Summer'
  trigger:
    - platform: numeric_state
      entity_id: sensor.upstairs_temp
      above: 22
      for:
        hours: 48
    - platform: numeric_state
      entity_id: sensor.downstairs_temp
      above: 22
      for:
        hours: 48
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.mode_climate
        option: "Summer"

- alias: 'Climate/ClimateMode/Winter'
  trigger:
    - platform: numeric_state
      entity_id: sensor.upstairs_temp
      below: 21
      for:
        hours: 48
    - platform: numeric_state
      entity_id: sensor.downstairs_temp
      below: 21
      for:
        hours: 48
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.mode_climate
        option: "Winter"