- alias: Environment/Air/Purifier/NoiseON
  id: '2022051400004'
  trigger:
    - platform: state
      entity_id: 'switch.preference_noisy_automations'
      to: 'on' 
  action:
    service: automation.trigger
    data:
      skip_condition: false
    target:
      entity_id: 
        - fan.air_purifier_cinema_room
        - fan.air_purifier_livingroom
        - fan.air_purifier_office

- alias: Environment/Air/Purifier/NoiseOFF
  id: '2022051400005'
  trigger:
    - platform: state
      entity_id: 'switch.preference_noisy_automations'
      to: 'off' 
  action:
    - service: fan.turn_off
      entity_id: 
        - fan.air_purifier_cinema_room
        - fan.air_purifier_livingroom
        - fan.air_purifier_office

- alias: Environment/Air/Purifier/AlergyMonths
  id: '2022112200001'
  trigger:
    - platform: time
      at: "12:30:00"
    - platform: sun
      event: sunset
      offset: "-00:10:00"
  condition:
    - condition: state
      entity_id: switch.preference_noisy_automations
      state: "on"
    - condition: state
      entity_id: input_boolean.mode_holidays
      state: "off"
    - condition: template
      value_template: '{{ now().month in [3,4,5,6] }}'
  action:
    - service: fan.turn_on
      entity_id: 
        - fan.air_purifier_cinema_room
        - fan.air_purifier_livingroom
        - fan.air_purifier_office
    - wait_template: "{{ is_state('switch.preference_noisy_automations', 'off') }}"
      timeout: "00:30:00"
    - service: fan.turn_off
      entity_id: 
        - fan.air_purifier_cinema_room
        - fan.air_purifier_livingroom
        - fan.air_purifier_office


- alias: Environment/Air/Purifier/CinemaRoom/PM
  id: '2022051400001'
  trigger:
    - platform: numeric_state
      entity_id: sensor.air_purifier_cinema_room_pm2_5
      above: 6
  condition:
    - condition: state
      entity_id: switch.preference_noisy_automations
      state: 'on'
    - condition: state
      entity_id: input_boolean.mode_holidays
      state: "off"
    - condition: numeric_state
      entity_id: sensor.air_purifier_cinema_room_pm2_5
      above: 6
  action:
    - service: fan.turn_on
      entity_id: fan.air_purifier_cinema_room
    - delay: "00:05:00"
    - wait_template: "{{states('sensor.air_purifier_cinema_room_pm2_5') | int <= 2 }}"
      timeout: "01:00:00"
    - delay: "00:01:00"
    - service: fan.turn_off
      entity_id: fan.air_purifier_cinema_room

- alias: Environment/Air/Purifier/Office/PM
  id: '2022051400002'
  trigger:
    - platform: numeric_state
      entity_id: sensor.air_purifier_office_pm2_5
      above: 6
  condition:
    - condition: state
      entity_id: switch.preference_noisy_automations
      state: 'on'
    - condition: state
      entity_id: input_boolean.mode_holidays
      state: "off"
    - condition: numeric_state
      entity_id: sensor.air_purifier_office_pm2_5
      above: 6
  action:
    - service: fan.turn_on
      entity_id: fan.air_purifier_office
    - delay: "00:10:00"
    - wait_template: "{{states('sensor.air_purifier_office_pm2_5') | int <= 1 }}"
      timeout: "01:00:00"
    - delay: "00:05:00"
    - service: fan.turn_off
      entity_id: fan.air_purifier_office


- alias: Environment/Air/Purifier/LRoom/PM
  id: '2022051400003'
  trigger:
    - platform: numeric_state
      entity_id: sensor.air_purifier_living_room_pm2_5
      above: 6
  condition:
    - condition: state
      entity_id: switch.preference_noisy_automations
      state: 'on'
    - condition: state
      entity_id: input_boolean.mode_holidays
      state: "off"
    - condition: numeric_state
      entity_id: sensor.air_purifier_living_room_pm2_5
      above: 6
  action:
    - service: fan.turn_on
      entity_id: fan.air_purifier_livingroom
    - delay: "00:10:00"
    - wait_template: "{{states('sensor.air_purifier_living_room_pm2_5') | int <= 1 }}"
      timeout: "01:00:00"
    - delay: "00:05:00"
    - service: fan.turn_off
      entity_id: fan.air_purifier_livingroom


- alias: Environment/Humidity/DehumidifiersAutoSetting
  id: '2021122500001'
  trigger:
    - platform: state
      entity_id: 
        - sensor.maximum_allowed_humidity
        - input_number.dehumidifiers_ht
  action:
    - service: humidifier.set_humidity
      target:
        entity_id:
          - humidifier.downstairs
          - humidifier.upstairs
      data:
        humidity: >-
          {% if states('sensor.maximum_allowed_humidity') | int > states('input_number.dehumidifiers_ht') | int %}
            {{states('input_number.dehumidifiers_ht') | int}}
          {% else %}
            {{states('sensor.maximum_allowed_humidity') | int}}
          {% endif %}
          
- alias: Environment/FireplaceHeatRecovery2
  id: '2022010700001'
  trigger:
    - platform: state
      entity_id: 
        - sensor.fireplace_secondary_heat_recovery_temp
        - switch.preference_noisy_automations
  action:
    - choose:
      - alias: "FireplaceHeatRecovery2/ON/NoiseON"
        conditions:
        - condition: state
          entity_id: switch.preference_noisy_automations
          state: 'on'
        - condition: numeric_state
          entity_id: sensor.fireplace_secondary_heat_recovery_temp
          above: 40
          below: 61
        sequence:
          service: fan.set_percentage
          data:
            percentage: "{{ states('sensor.fireplace_secondary_heat_recovery_temp')|int*4.25 - 155 }}"
          target:
            entity_id: fan.fireplace_secondary_heat_recovery_fan

      - alias: "FireplaceHeatRecovery2/ON/NoiseOFFHighTemp"
        conditions:
        - condition: state
          entity_id: switch.preference_noisy_automations
          state: 'off'
        - condition: numeric_state
          entity_id: sensor.fireplace_secondary_heat_recovery_temp
          above: 60
        sequence:
          service: fan.set_percentage
          data:
            percentage: 70
          target:
            entity_id: fan.fireplace_secondary_heat_recovery_fan

      - alias: "FireplaceHeatRecovery2/ON/NoiseONHighTemp"
        conditions:
        - condition: state
          entity_id: switch.preference_noisy_automations
          state: 'on'
        - condition: numeric_state
          entity_id: sensor.fireplace_secondary_heat_recovery_temp
          above: 60
        sequence:
          service: fan.set_percentage
          data:
            percentage: 100
          target:
            entity_id: fan.fireplace_secondary_heat_recovery_fan

      - alias: "FireplaceHeatRecovery2/ON/NoiseOFF"
        conditions:
        - condition: state
          entity_id: switch.preference_noisy_automations
          state: 'off'
        - condition: numeric_state
          entity_id: sensor.fireplace_secondary_heat_recovery_temp
          above: 40
          below: 61
        sequence:
          service: fan.set_percentage
          data:
            percentage: "{{ states('sensor.fireplace_secondary_heat_recovery_temp')|int*2.5 - 80 }}"
          target:
            entity_id: fan.fireplace_secondary_heat_recovery_fan

      - alias: "FireplaceHeatRecovery2/OFF"
        conditions:
        - condition: numeric_state
          entity_id: sensor.fireplace_secondary_heat_recovery_temp
          below: 40
        sequence:
          service: fan.turn_off
          target:
            entity_id: fan.fireplace_secondary_heat_recovery_fan

