- alias: Environment/Air/Purifier/CinemaRoom/On
  id: '2021120300001'
  trigger:
    - platform: numeric_state
      entity_id: 'sensor.air_purifier_cinema_room_pm2_5'
      above: 6
      for:
        minutes: 2
    - platform: state
      entity_id: 'switch.preference_noisy_automations'
      to: 'on' 
  condition:
    - condition: state
      entity_id: 'switch.preference_noisy_automations'
      state: 'on'
    - condition: numeric_state
      entity_id: sensor.air_purifier_cinema_room_pm2_5
      above: 6
  action:
    - service: fan.turn_on
      entity_id: 'fan.air_purifier_cinema_room'

- alias: Environment/Air/Purifier/CinemaRoom/Off
  id: '2021120300002'
  trigger:
    - platform: numeric_state
      entity_id: sensor.air_purifier_cinema_room_pm2_5
      below: 5
      for:
        minutes: 5
    - platform: state
      entity_id: 'switch.preference_noisy_automations'
      to: 'off' 
  action:
    - service: fan.turn_off
      entity_id: 'fan.air_purifier_cinema_room'

- alias: Environment/Air/Purifier/Office/On
  id: '2021120300003'
  trigger:
    - platform: numeric_state
      entity_id: sensor.air_purifier_office_pm2_5
      above: 6
      for:
        minutes: 2
    - platform: state
      entity_id: 'switch.preference_noisy_automations'
      to: 'on' 
  condition:
    - condition: state
      entity_id: 'switch.preference_noisy_automations'
      state: 'on'
    - condition: numeric_state
      entity_id: sensor.air_purifier_office_pm2_5
      above: 6
  action:
    - service: fan.turn_on
      entity_id: 'fan.air_purifier_office'

- alias: Environment/Air/Purifier/Office/Off
  id: '2021120300004'
  trigger:
    - platform: numeric_state
      entity_id: sensor.air_purifier_office_pm2_5
      below: 5
      for:
        minutes: 5
    - platform: state
      entity_id: 'switch.preference_noisy_automations'
      to: 'off' 
  action:
    - service: fan.turn_off
      entity_id: 'fan.air_purifier_office'

- alias: Environment/Humidity/DehumidifiersAutoSetting
  id: '2021122500001'
  trigger:
    - platform: state
      entity_id: 
        - sensor.maximum_allowed_humidity
        - input_number.dehumidifiers_ht
  action:
    - service: humidifier.set_humidity
      target:
        entity_id:
          - humidifier.downstairs
          - humidifier.upstairs
      data:
        humidity: >-
          {% if states('sensor.maximum_allowed_humidity') | int > states('input_number.dehumidifiers_ht') | int %}
            {{states('input_number.dehumidifiers_ht') | int}}
          {% else %}
            {{states('sensor.maximum_allowed_humidity') | int}}
          {% endif %}
          
- alias: Environment/FireplaceHeatRecovery2
  id: '2022010700001'
  trigger:
    - platform: state
      entity_id: 
        - sensor.fireplace_secondary_heat_recovery_temp
        - switch.preference_noisy_automations
  action:
    - choose:
      - alias: "FireplaceHeatRecovery2/ON/NoiseON"
        conditions:
        - condition: state
          entity_id: switch.preference_noisy_automations
          state: 'on'
        - condition: numeric_state
          entity_id: sensor.fireplace_secondary_heat_recovery_temp
          above: 40
          below: 61
        sequence:
          service: fan.set_percentage
          data:
            percentage: "{{ states('sensor.fireplace_secondary_heat_recovery_temp')|int*4.25 - 155 }}"
          target:
            entity_id: fan.fireplace_secondary_heat_recovery_fan

      - alias: "FireplaceHeatRecovery2/ON/NoiseOFF"
        conditions:
        - condition: state
          entity_id: switch.preference_noisy_automations
          state: 'off'
        - condition: numeric_state
          entity_id: sensor.fireplace_secondary_heat_recovery_temp
          above: 40
          below: 61
        sequence:
          service: fan.set_percentage
          data:
            percentage: "{{ states('sensor.fireplace_secondary_heat_recovery_temp')|int*2.5 - 80 }}"
          target:
            entity_id: fan.fireplace_secondary_heat_recovery_fan

      - alias: "FireplaceHeatRecovery2/OFF"
        conditions:
        - condition: numeric_state
          entity_id: sensor.fireplace_secondary_heat_recovery_temp
          below: 40
        sequence:
          service: fan.turn_off
          target:
            entity_id: fan.fireplace_secondary_heat_recovery_fan

