- alias: 'HomeAssistant Start'
  trigger:
    platform: homeassistant
    event: start
  action:
    - delay: 30
    - service: mqtt.publish
      data_template:
        topic: 'shellies/command'
        payload: 'announce'
    - service: input_select.select_option
      data:
        entity_id: input_select.mode_climate
        option: "Summer"
    - condition: or
      conditions:
        - condition: template
          value_template: '{{ states.sensor.downstairs_temp.state | float < 22 }}'
    - service: input_select.select_option
      data:
        entity_id: input_select.mode_climate
        option: "Winter"

- alias: "Core/UpdateTemplateSensors"
  trigger:
    platform: time_pattern
    hours: "*"
  action:
    - service: homeassistant.update_entity
      entity_id: sensor.electricity_rate_next_switch
    - service: homeassistant.update_entity
      entity_id: sensor.electricity_rate

- alias: "Core/RequestShellyAnnounce"
  trigger:
    platform: time_pattern
    hours: "*"
  action:
    - service: mqtt.publish
      data:
        topic: shellies/command
        payload: announce


