- alias: 'Turn perimeter lights on'
  trigger:
    - platform: sun
      event: sunset
      offset: "+00:15:00"
    - platform: time
      at: '06:00:00'
  condition:
    - condition: or
      conditions:
        - condition: sun
          before: sunrise
          before_offset: "-00:45:00"
        - condition: sun
          after: sunset
  action:
    service: homeassistant.turn_on
    entity_id: group.perimeter_lights

- alias: 'Turn perimeter lights off'
  trigger:
    - platform: time
      at: '02:00:00'
    - platform: sun
      event: sunrise
      offset: "-00:30:00"
  action:
    service: homeassistant.turn_off
    entity_id: group.perimeter_lights

