- alias: 'Turn perimeter lights on'
  trigger:
    - platform: sun
      event: sunset
      offset: "+00:15:00"
    - platform: time
      at: '06:00:00'
  condition:
    - condition: or
      conditions:
        - condition: sun
          before: sunrise
          before_offset: "-00:45:00"
        - condition: sun
          after: sunset
  action:
    service: light.turn_on
    entity_id: light.perimeter_lights

- alias: 'Turn perimeter lights off'
  trigger:
    - platform: time
      at: '02:00:00'
    - platform: sun
      event: sunrise
      offset: "-00:30:00"
  action:
    service: light.turn_off
    entity_id: light.perimeter_lights

- alias: 'Outside/Garder/WaterDepositRefill'
  id: '1617198475391'
  trigger:
    - platform: time
      at: '3:00:00'
    - platform: numeric_state
      entity_id: sensor.utility_power
      below: -300
      for:
        minutes: 5
  condition:
    - condition: numeric_state
      entity_id: sensor.outside_waterdeposit_level
      below: 95
  action:
    - choose:
      - alias: "Outside/Garder/WaterDepositRefill/SolarPower"
        conditions:
        - condition: numeric_state
          entity_id: sensor.utility_power
          below: -300
        sequence:
          - service: switch.turn_on
            entity_id: switch.well_pump 
          - wait_template: "{{ (states.sensor.outside_waterdeposit_level.state|int) > 98 }}"
            timeout: '00:05:00'
          - wait_template: "{{ ((states.sensor.outside_waterdeposit_level.state|int) > 98) or (states.sensor.utility_power.state | int > -10) }}"
          - service: switch.turn_off
            entity_id: switch.well_pump

      - alias: "Outside/Garder/WaterDepositRefill/NightTarif"
        conditions:
        - condition: numeric_state
          entity_id: sensor.outside_waterdeposit_level
          below: 40
        sequence:
          - service: switch.turn_on
            entity_id: switch.well_pump
          - wait_template: "{{ (states.sensor.outside_waterdeposit_level.state|int) > 90}}"
            timeout: '00:20:00'
          - service: switch.turn_off
            entity_id: switch.well_pump
