- alias: 'Family away'
  trigger:
    platform: state
    entity_id: group.family
    from: 'home'
    to: 'not_home'
    for:
      minutes: 10
  action:
    - service: automation.trigger
      data:
        entity_id: automation.water_gasbackup_on
        skip_condition: 'false'
    - service: switch.turn_on
      data:
        entity_id: switch.dehumidifier
    - service: cover.set_cover_position
      data_template:
        entity_id: "{% set ns = namespace(comma=false) %}{%- for roller in states.group.shutters_downstairs.attributes.entity_id -%}{%- if state_attr(roller,'current_position') > 20 %}{% if ns.comma %},{% endif %}{% set ns.comma = true %}{{ roller }}{% endif -%}{%- endfor %}"
        position: 15


- alias: 'Someone home'
  trigger:
    platform: state
    entity_id: group.family
    from: 'not_home'
    to: 'home'
    for:
      minutes: 6
  action:
    - service: automation.trigger
      data:
        entity_id: automation.water_gasbackup_off
        skip_condition: 'false'
    - service: switch.turn_off
      data:
        entity_id: switch.dehumidifier
