- alias: 'Plugs/TowelHeater/Winter'
  id: '2023102000001'
  trigger:
    - platform: numeric_state
      entity_id: sensor.minutes_next_mainroom_alarm
      below: 60
  condition:
    - condition: state
      entity_id: input_select.mode_climate
      state: 'Winter'
    - condition: state
      entity_id: binary_sensor.workday_sensor
      state: 'on'
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.towel_heater
    - delay: 2:30:00
    - service: switch.turn_off
      data:
        entity_id: switch.towel_heater

- alias: 'Plugs/TowelHeater/Summer'
  id: '2023102000002'
  trigger:
    - platform: numeric_state
      entity_id: sensor.minutes_next_mainroom_alarm
      below: 15
  condition:
    - condition: state
      entity_id: input_select.mode_climate
      state: 'Summer'
    - condition: state
      entity_id: binary_sensor.workday_sensor
      state: 'on'
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.towel_heater
    - delay: 1:30:00
    - service: switch.turn_off
      data:
        entity_id: switch.towel_heater
