- alias: 'Plugs/MediaRoom/Main/SyncOn'
  trigger:
    platform: state
    entity_id: switch.mediaroom_main
    to: "on"
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.mediaroom_back

- alias: 'Plugs/MediaRoom/Main/SyncOff'
  trigger:
    platform: state
    entity_id: switch.mediaroom_main
    to: "off"
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.mediaroom_back

- alias: 'Button/Mediaroom/MainPower'
  trigger:
    platform: webhook
    webhook_id: a53b8ea0-41b1-4063-a3a3-1f32b046d5f6
    local_only: true
  action:
    - service: switch.toggle
      data:
        entity_id: switch.mediaroom_main

- alias: 'Button/Mediaroom/CeilingLight'
  trigger:
    platform: webhook
    webhook_id: 767460cf-56df-47e4-bab8-627193c615b5
    local_only: true
  action:
    - service: light.toggle
      data:
        entity_id: light.living_room_dinning_light

  