- alias: 'Lights/LivingRoom/On'
  trigger:
    - platform: state
      entity_id: 'binary_sensor.f_5im51_103_20'
      from: 'off'
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: 'light.living_room_leds'
        state: 'off'
      - condition: state
        entity_id: 'input_select.mode_lights_livingroom'
        state: 'Auto'
      - condition: template
        value_template: '{{ states.sensor.f_5im51_103_13.state | int < 10}}'
  action:
      - service: light.turn_on
        data:
          entity_id: light.living_room_leds
          brightness: 60

- alias: 'Lights/LivingRoom/Off'
  trigger:
    - platform: state
      entity_id: 'binary_sensor.f_5im51_103_20'
      from: 'on'
      to: 'off'
      for:
        minutes: 10
  condition:
    condition: and
    conditions:
      - condition: or
        conditions:
          - condition: state
            entity_id: 'input_select.mode_lights_livingroom'
            state: 'Auto'
          - condition: state
            entity_id: 'input_select.mode_lights_livingroom'
            state: 'Auto off'
      - condition: state
        entity_id: 'light.living_room_leds'
        state: 'on'
  action:
      - service: light.turn_off
        data:
          entity_id: light.living_room_leds





- alias: 'Lights/DownstairsHall/On'
  trigger:
    platform: state
    entity_id: 'binary_sensor.f_5im51_102_20'
    from: 'off'
    to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: light.downhall_lights
        state: "off"
      - condition: state
        entity_id: input_select.mode_lights_downstairshall
        state: "Auto"
      - condition: template
        value_template: '{{ states.sensor.f_5im51_103_13.state | int < 10}}'
  action:
      - service: light.turn_on
        data:
          entity_id: light.downhall_lights

- alias: 'Lights/DownstairsHall/Off'
  trigger:
    - platform: state
      entity_id: 'binary_sensor.f_5im51_102_20'
      from: 'on'
      to: 'off'
      for:
        minutes: 1
  condition:
    condition: and
    conditions:
      - condition: or
        conditions:
          - condition: state
            entity_id: 'input_select.mode_lights_downstairshall'
            state: 'Auto'
          - condition: state
            entity_id: 'input_select.mode_lights_downstairshall'
            state: 'Auto off'
      - condition: state
        entity_id: 'light.downhall_lights'
        state: 'on'
  action:
      - service: light.turn_off
        data:
          entity_id: light.downhall_lights
