- alias: 'Status/FamilyAsleep/On'
  trigger:
    - platform: state
      entity_id: group.lights_downstairs
      to: "off"
      for:
        minutes: 15
    - platform: state
      entity_id: group.motion_downstairs
      to: "off"
      for:
        minutes: 15
    - platform: state
      entity_id: group.lights_upstairs
      to: "off"
      for:
        minutes: 15
    - platform: state
      entity_id: group.motion_upstairs
      to: "off"
      for:
        minutes: 15
    - platform: state
      entity_id: binary_sensor.lroom_media_state
      to: "off"
      for:
        minutes: 15
    - platform: state
      entity_id: 'cover.mary_s_room_shutter'
      from: 'open'
      to: 'closed'
    - platform: state
      entity_id: 'cover.maggie_s_room_shutter'
      from: 'open'
      to: 'closed'
    - platform: state
      entity_id: 'cover.main_room_shutter'
      from: 'open'
      to: 'closed'
  condition:
    - condition: or
      conditions:
        - condition: sun
          after: sunset
          after_offset: "01:00:00"
        - condition: sun
          before: sunrise
          after_offset: "-03:00:00"
    - condition: state
      entity_id: group.family
      state: "home"
    - condition: state
      entity_id: switch.status_family_sleeping
      state: "off"
    - condition: state
      entity_id: group.lights_downstairs
      state: "off"
    - condition: state
      entity_id: group.motion_downstairs
      state: "off"
    - condition: state
      entity_id: group.lights_upstairs
      state: "off"
    - condition: state
      entity_id: group.motion_upstairs
      state: "off"
    - condition: state
      entity_id: binary_sensor.lroom_media_state
      state: "off"
    - condition: state
      entity_id: 'cover.mary_s_room_shutter'
      state: 'closed'
    - condition: state
      entity_id: 'cover.maggie_s_room_shutter'
      state: 'closed'
    - condition: state
      entity_id: 'cover.main_room_shutter'
      state: 'closed'
  action:
    - service: switch.turn_on
      entity_id: switch.status_family_sleeping


- alias: 'Status/FamilyAsleep/Off'
  trigger:
    - platform: state
      entity_id: 'cover.mary_s_room_shutter'
      from: 'closed'
      to: 'open'
    - platform: state
      entity_id: 'cover.maggie_s_room_shutter'
      from: 'closed'
      to: 'open'
    - platform: state
      entity_id: 'cover.main_room_shutter'
      from: 'closed'
      to: 'open'
  condition:
    - condition: sun
      after: sunrise
      after_offset: "-02:00:00"
    - condition: state
      entity_id: switch.status_family_sleeping
      state: "on"
    - condition: state
      entity_id: 'cover.mary_s_room_shutter'
      state: 'open'
    - condition: state
      entity_id: 'cover.maggie_s_room_shutter'
      state: 'open'
    - condition: state
      entity_id: 'cover.main_room_shutter'
      state: 'open'
  action:
    - service: switch.turn_off
      entity_id: switch.status_family_sleeping

- alias: 'Status/FamilyPresence/ArrivingHome'
  trigger:
    - platform: state
      entity_id: group.family
      from: 'not_home'
      to: 'home'
      for:
        minutes: 1
  action:
    - service: mqtt.publish
      data:
        topic: "home/l/status/family_presence"
        payload: "arriving"
        qos: 2
        retain: true
    - wait_template: "{{ states.binary_sensor.front_door_contact_sensor.state == 'on' }}"
      timeout: '00:05:00'
    - service: mqtt.publish
      data:
        topic: "home/l/status/family_presence"
        payload: "home"
        qos: 2
        retain: true

- alias: 'Status/FamilyPresence/LeavingHome'
  trigger:
    - platform: state
      entity_id: group.family
      from: 'home'
      to: 'not_home'
  condition:
    - condition: state
      entity_id: group.family
      state: "not_home"
  action:
    - service: mqtt.publish
      data:
        topic: "home/l/status/family_presence"
        payload: "not_home"
        qos: 2
        retain: true


