- alias: 'UtilityMeters/Peak'
  trigger:
    - platform: homeassistant
      event: start
    - platform: state
      entity_id: sensor.electricity_rate
  condition:
    - condition: state
      entity_id: sensor.electricity_rate
      state: 'Peak'
  action:
    - service: select.select_option
      target:
        entity_id: select.daily_energy_in
      data:
        option: "peak"
    - service: utility_meter.select_tariff
      target:
        entity_id: select.daily_energy_out
      data:
        option: "peak"
    - service: utility_meter.select_tariff
      target:
        entity_id: select.monthly_energy_in
      data:
        option: "peak"
    - service: utility_meter.select_tariff
      target:
        entity_id: select.daily_solar_energy
      data:
        option: "peak"
    - service: utility_meter.select_tariff
      target:
        entity_id: select.monthly_solar_energy
      data:
        option: "peak"

- alias: 'UtilityMeters/OffPeak'
  trigger:
    - platform: homeassistant
      event: start
    - platform: state
      entity_id: sensor.electricity_rate
  condition:
    - condition: state
      entity_id: sensor.electricity_rate
      state: 'Off-peak'
  action:
    - service: select.select_option
      target:
        entity_id: select.daily_energy_in
      data:
        option: "offpeak"
    - service: utility_meter.select_tariff
      target:
        entity_id: select.daily_energy_out
      data:
        option: "offpeak"
    - service: utility_meter.select_tariff
      target:
        entity_id: select.monthly_energy_in
      data:
        option: "offpeak"
    - service: utility_meter.select_tariff
      target:
        entity_id: select.daily_solar_energy
      data:
        option: "offpeak"
    - service: utility_meter.select_tariff
      target:
        entity_id: select.monthly_solar_energy
      data:
        option: "offpeak"
