- alias: 'Vacuum/All/Clean'
  trigger:
    - platform: state
      entity_id: sensor.family_presence
      from: 'home'
      to: 'not_home'
      for:
        minutes: 30
  condition:
  - condition: and
    conditions:
    - condition: time
      weekday:
      - mon
      - wed
      - fri
    - condition: state
      entity_id: 'group.family'
      state: 'not_home'
    - condition: state
      entity_id: 'switch.preference_noisy_automations'
      state: 'on'
  action:
    - service: vacuum.start
      data:
        entity_id: vacuum.dusty
    - service: vacuum.start
      data:
        entity_id: vacuum.rosie

- alias: 'Vacuum/All/StopWhenHome'
  trigger:
    platform: state
    entity_id: sensor.family_presence
    from: 'arriving'
    to: 'home'
  action:
    - if:
        - condition: state
          entity_id: vacuum.rosie
          state: 'cleaning'
      then:
        - service: vacuum.return_to_base
          data:
            entity_id: vacuum.dusty
    - if:
        - condition: state
          entity_id: vacuum.rosie
          state: 'cleaning'
      then:
        - service: vacuum.return_to_base
          data:
            entity_id: vacuum.rosie
