- alias: 'Vacuum/Kitchen/CleanAfterDinnerWeekdays'
  id: '2023121300001'
  trace:
    stored_traces: 20
  trigger: 
    - platform: state
      entity_id: "binary_sensor.f_5im51_104_20"
      to: "off"
      for:
        minutes: 15
    - platform: state
      entity_id: light.kitchen_spots
      to: "off"
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
    - condition: template
      value_template: "{{(as_timestamp(now())-as_timestamp(states.sensor.last_kitchen_autovacuum.state)) > 43200}}"
    - condition: state
      entity_id: light.kitchen_spots
      state: "off"
    - condition: state
      entity_id: light.kitchen_table
      state: "off"
    - condition: state
      entity_id: binary_sensor.f_5im51_104_20
      state: "off"
      for:
        minutes: 15
    - condition: time
      after: "19:30:00"
      before: "21:15:00"
  action:
    - service: vacuum.send_command
      data:
        entity_id: vacuum.rosie
        command: start
        params:
          pmap_id: 6zrzysUwTwqmEx4a0a5W0Q
          ordered: 1
          regions:
            - region_id: '4'
              type: rid           
          user_pmapv_id: 240310T122731
    - service: mqtt.publish
      data:
        topic: "home/l/data/kitchenautocleanlastrun"
        payload_template: "{{ now() }}"
        retain: "true"

- alias: 'Vacuum/Kitchen/CleanAfterDinnerWeekend'
  id: '2023121300002'
  trace:
    stored_traces: 20
  trigger: 
    - platform: state
      entity_id: "binary_sensor.f_5im51_104_20"
      to: "off"
      for:
        minutes: 15
    - platform: state
      entity_id: light.kitchen_spots
      to: "off"
  condition:
    - condition: time
      weekday:
        - fri
        - sat
        - sun
    - condition: template
      value_template: "{{(as_timestamp(now())-as_timestamp(states.sensor.last_kitchen_autovacuum.state)) > 43200}}"
    - condition: state
      entity_id: light.kitchen_spots
      state: "off"
    - condition: state
      entity_id: light.kitchen_table
      state: "off"
    - condition: state
      entity_id: binary_sensor.f_5im51_104_20
      state: "off"
    - condition: time
      after: "19:30:00"
      before: "21:45:00"
  action:
    - service: vacuum.send_command
      data:
        entity_id: vacuum.rosie
        command: start
        params:
          pmap_id: 6zrzysUwTwqmEx4a0a5W0Q
          ordered: 1
          regions:
            - region_id: '4'
              type: rid           
          user_pmapv_id: 240310T122731
    - service: mqtt.publish
      data:
        topic: "home/l/data/kitchenautocleanlastrun"
        payload_template: "{{ now() }}"
        retain: "true"


- alias: 'Vacuum/All/Clean'
  id: '2023121300003'
  trigger:
    - platform: state
      entity_id: sensor.family_presence
      from: 'home'
      to: 'not_home'
      for:
        minutes: 30
  condition:
  - condition: and
    conditions:
    - condition: time
      weekday:
      - mon
      - wed
      - fri
    - condition: state
      entity_id: 'group.family'
      state: 'not_home'
    - condition: state
      entity_id: 'switch.preference_noisy_automations'
      state: 'on'
  action:
    - service: vacuum.start
      data:
        entity_id: vacuum.dusty
    - service: vacuum.start
      data:
        entity_id: vacuum.rosie

- alias: 'Vacuum/Upstairs/Clean'
  id: '2024022500001'
  trigger:
    - platform: time
      at: "19:30:00"
  condition:
  - condition: and
    conditions:
    - condition: time
      weekday:
      - tue
      - thu
    - condition: state
      entity_id: 'switch.preference_noisy_automations'
      state: 'on'
  action:
    - service: vacuum.start
      data:
        entity_id: vacuum.dusty

- alias: 'Vacuum/All/StopWhenHome'
  id: '2023121300004'
  trigger:
    platform: state
    entity_id: sensor.family_presence
    from: 'arriving'
    to: 'home'
  action:
    - if:
        - condition: state
          entity_id: vacuum.rosie
          state: 'cleaning'
      then:
        - service: vacuum.return_to_base
          data:
            entity_id: vacuum.dusty
    - if:
        - condition: state
          entity_id: vacuum.rosie
          state: 'cleaning'
      then:
        - service: vacuum.return_to_base
          data:
            entity_id: vacuum.rosie
